site_name: TuGraph Documentation
site_dir: docs
docs_dir: doc
theme: readthedocs
nav:
  - Home: index.md
  - en-US:
      - Guide:
          - What is Graph: en-US/1.guide/1.what-is-graph.md
          - What is GDBMS: en-US/1.guide/2.what-is-GDBMS.md
          - Quick Start: en-US/1.guide/3.quick-start.md
      - Operating:
          - Introduction: en-US/2.operating/1.introduce.md
          - Install: en-US/2.operating/2.Install.md
          - Data Import: en-US/2.operating/3.data-import.md
          - Server Config: en-US/2.operating/4.server-config.md
          - Operation: en-US/2.operating/5.operation.md
          - HA Mode: en-US/2.operating/7.ha-mode.md
          - Manage Database: en-US/2.operating/8.manage-database.md
          - Privilege: en-US/2.operating/9.privilege.md
          - Tools:
              - TuGraph Cypher: en-US/2.operating/6.tools/1.tugraph-cypher.md
              - TuGraph Browser: en-US/2.operating/6.tools/2.tugraph-browser.md
              - TuGraph DataX: en-US/2.operating/6.tools/3.tugraph-datax.md
              - TuGraph Explore: en-US/2.operating/6.tools/4.tugraph-explore.md
      - Developer Document:
          - RESTful API: en-US/3.developer-document/1.restful-api.md
          - Cypher: en-US/3.developer-document/2.cypher.md
          - Procedure: en-US/3.developer-document/3.procedure.md
          - Graph Analytics Engine:
              - Tutorial: en-US/3.developer-document/4.graph_analytics_engine/1.tutorial.md
              - OLAP Base API: en-US/3.developer-document/4.graph_analytics_engine/2.olap-base-api.md
              - OLAP on DB API: en-US/3.developer-document/4.graph_analytics_engine/3.olap-on-db-api.md
              - OLAP on Disk API: en-US/3.developer-document/4.graph_analytics_engine/4.olap-on-disk-api.md
              - Algorithms: en-US/3.developer-document/4.graph_analytics_engine/5.algorithms.md
              - Python API: en-US/3.developer-document/4.graph_analytics_engine/6.python-api.md
      - Client:
          - Java Client: en-US/4.client/1.java-client.md
          - Python Client: en-US/4.client/2.python-client.md
          - CPP Client: en-US/4.client/3.cpp-client.md
      - Supplement:
          - Changelog: en-US/5.supplement/changelog.md
      - Community:
          - Contributing: en-US/6.community/1.contributing.md
          - Membership: en-US/6.community/2.membership.md
          - Roadmap: en-US/6.community/3.roadmap.md
          - Individual CLA: en-US/6.community/4.individual_cla.md
          - Corporate CLA: en-US/6.community/5.corporate_cla.md
